[package]
name = "auth"
version.workspace = true
edition.workspace = true

[dependencies]
actix-session.workspace = true
actix-web.workspace = true
async-trait.workspace = true
log.workspace = true
openidconnect.workspace = true
serde.workspace = true
