name: Deployment
on:
  release:
    types:
      - published

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push (Frontend)
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: false
          context: ./frontend
          tags: |
            ${{ vars.REGISTRY }}/${{ vars.IMAGE_REPO_FRONTEND }}:latest
            ${{ vars.REGISTRY }}/${{ vars.IMAGE_REPO_FRONTEND }}:${{ gitea.event.release.tag_name }}

      - name: Build and push (Backend)
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: false
          context: ./backend
          tags: |
            ${{ vars.REGISTRY }}/${{ vars.IMAGE_REPO_BACKEND }}:latest
            ${{ vars.REGISTRY }}/${{ vars.IMAGE_REPO_BACKEND }}:${{ gitea.event.release.tag_name }}
