[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
actix-web.workspace = true
dotenv.workspace = true
env_logger.workspace = true
percent-encoding.workspace = true
sqlx.workspace = true

image.workspace = true
post.workspace = true
